tables = [
    {
        'name': 'articles',
        'schema': {
            "site_id": "string",
            "article_id": "string",
            "title": "string",
            "author": "string",
            "author_id": "string",
            "category": "string",
            "published_date": "Datetime",
            "created_at": "Datetime",
            "org_id": "Integer"
        }
    },
    {
        "name": "articles_daily",
        "schema": {
            "site_id": "string",
            "period_date": "string",
            "article_id": "string",
            "page_views": "string",
            "title": "string",
            "author": "string",
            "author_id": "string",
            "new_users": "string",
            "bounce_rate": "string",
            "pageviews_per_session": "string",
            "sessions_per_user": "string",
            "users": "string",
            "attention_time": "string",
            "created_at": "string",
            "frequency": "string",
            "total_shares": "Integer",
            "key_words": "string",
            "exit_page_distribution": "string",
            "total_time_spent": "Integer",
            "average_time_spent": "Integer",
            "country_distribution": "string",
            "city_distribution": "string",
            "referrer_distribution": "string",
            "device_distribution": "string",
            "social_distribution": "string",
            "org_id": "Integer"
        }
    },
    {
        "name": "authors",
        "schema": {
            "site_id": "string",
            "name": "string",
            "author_id": "string",
            "created_at": "DateTime",
            "org_id": "Integer"
        }
    },
    {
        "name": "authors_daily",
        "schema": {
            "site_id": "string",
            "page_views": "Integer",
            "author": "string",
            "author_id": "string",
            "users": "Integer",
            "period_date": "string",
            "attention_time": "Integer",
            "created_at": "dateTime",
            "time_of_day": "string",
            "frequency": "String",
            "key_words": "String",
            "exit_page_distribution": "String",
            "total_time_spent": "Integer",
            "average_time_spent": "Integer",
            "source_distribution": "String",
            "medium_distribution": "String",
            "country_distribution": "String",
            "country_wise_city": "String",
            "org_id": "Integer"
        }
    },
    {
        "name": "articles_monthly",
        "schema": {
            "site_id": "string",
            "period_month": "integer",
            "period_year": "integer",
            "article_id": "string",
            "page_views": "string",
            "title": "string",
            "author": "string",
            "author_id": "string",
            "new_users": "string",
            "bounce_rate": "string",
            "pageviews_per_session": "string",
            "sessions_per_user": "string",
            "users": "string",
            "attention_time": "string",
            "created_at": "string",
            "frequency": "string",
            "total_shares": "Integer",
            "key_words": "string",
            "exit_page_distribution": "string",
            "total_time_spent": "Integer",
            "average_time_spent": "Integer",
            "country_distribution": "string",
            "city_distribution": "string",
            "referrer_distribution": "string",
            "device_distribution": "string",
            "social_distribution": "string",
            "org_id": "Integer"
        }
    },
    {
        "name": "articles_quarterly",
        "schema": {
            "site_id": "string",
            "period_quarter": "integer",
            "period_year": "integer",
            "article_id": "string",
            "page_views": "string",
            "title": "string",
            "author": "string",
            "author_id": "string",
            "new_users": "string",
            "bounce_rate": "string",
            "pageviews_per_session": "string",
            "sessions_per_user": "string",
            "users": "string",
            "attention_time": "string",
            "created_at": "string",
            "frequency": "string",
            "total_shares": "Integer",
            "key_words": "string",
            "exit_page_distribution": "string",
            "total_time_spent": "Integer",
            "average_time_spent": "Integer",
            "country_distribution": "string",
            "city_distribution": "string",
            "referrer_distribution": "string",
            "device_distribution": "string",
            "social_distribution": "string",
            "org_id": "Integer"
        }
    },
    {
        "name": "articles_yearly",
        "schema": {
            "site_id": "string",
            "period_year": "integer",
            "article_id": "string",
            "page_views": "string",
            "title": "string",
            "author": "string",
            "author_id": "string",
            "new_users": "string",
            "bounce_rate": "string",
            "pageviews_per_session": "string",
            "sessions_per_user": "string",
            "users": "string",
            "attention_time": "string",
            "created_at": "string",
            "frequency": "string",
            "total_shares": "Integer",
            "key_words": "string",
            "exit_page_distribution": "string",
            "total_time_spent": "Integer",
            "average_time_spent": "Integer",
            "country_distribution": "string",
            "city_distribution": "string",
            "referrer_distribution": "string",
            "device_distribution": "string",
            "social_distribution": "string",
            "org_id": "Integer"
        }
    },
    {
        "name": "authors_monthly",
        "schema": {
            "site_id": "string",
            "page_views": "Integer",
            "author": "string",
            "author_id": "string",
            "users": "Integer",
            "period_month": "integer",
            "period_year": "integer",
            "attention_time": "Integer",
            "created_at": "dateTime",
            "time_of_day": "string",
            "frequency": "String",
            "key_words": "String",
            "exit_page_distribution": "String",
            "total_time_spent": "Integer",
            "average_time_spent": "Integer",
            "source_distribution": "String",
            "medium_distribution": "String",
            "country_distribution": "String",
            "country_wise_city": "String",
            "org_id": "Integer"
        }
    },
    {
        "name": "authors_quarterly",
        "schema": {
            "site_id": "string",
            "page_views": "Integer",
            "author": "string",
            "author_id": "string",
            "users": "Integer",
            "period_quarter": "integer",
            "period_year": "integer",
            "attention_time": "Integer",
            "created_at": "dateTime",
            "time_of_day": "string",
            "frequency": "String",
            "key_words": "String",
            "exit_page_distribution": "String",
            "total_time_spent": "Integer",
            "average_time_spent": "Integer",
            "source_distribution": "String",
            "medium_distribution": "String",
            "country_distribution": "String",
            "country_wise_city": "String",
            "org_id": "Integer"
        }
    },
    {
        "name": "authors_yearly",
        "schema": {
            "site_id": "string",
            "page_views": "Integer",
            "author": "string",
            "author_id": "string",
            "users": "Integer",
            "period_year": "integer",
            "attention_time": "Integer",
            "created_at": "dateTime",
            "time_of_day": "string",
            "frequency": "String",
            "key_words": "String",
            "exit_page_distribution": "String",
            "total_time_spent": "Integer",
            "average_time_spent": "Integer",
            "source_distribution": "String",
            "medium_distribution": "String",
            "country_distribution": "String",
            "country_wise_city": "String",
            "org_id": "Integer"
        }
    }
]